#pragma once

#include "FreeRTOS.h"
#include "stdbool.h"
#include "stdint.h"

typedef enum {
  SCREEN_AXIS_X = 0,
  SCREEN_AXIS_Y,
  SCREEN_AXIS_Z,

  SCREEN_AXIS_COUNT,
} screen_axis_t;

/* Acceleration values use 0.01 g as the unit. For example, 123 means 1.23 g. */
typedef struct {
  uint16_t current_centi_g[SCREEN_AXIS_COUNT];
  uint16_t peak_centi_g[SCREEN_AXIS_COUNT];
  bool alarm_active;
} screen_measurements_t;

typedef struct {
  bool enabled;
  uint16_t timeout_seconds;
} screen_auto_off_settings_t;

typedef struct {
  uint16_t min_centi_g[SCREEN_AXIS_COUNT];
  uint16_t max_centi_g[SCREEN_AXIS_COUNT];
  uint16_t trigger_period_ms;
  uint16_t trigger_count;
  uint16_t alarm_seconds;
  bool auto_stop_alarm;
  screen_auto_off_settings_t auto_off;
} screen_settings_t;

typedef enum {
  /* Persist and distribute the settings carried by this event. */
  SCREEN_EVENT_SETTINGS_COMMITTED = 0,
  /* Clear the recorded peak of the axis carried by this event. */
  SCREEN_EVENT_CLEAR_PEAK_REQUEST,
  /* Stop the active alarm, if any. */
  SCREEN_EVENT_ALARM_CANCEL_REQUEST,
} screen_event_type_t;

typedef struct {
  screen_event_type_t type;
  union {
    screen_settings_t settings;
    screen_axis_t axis;
  } data;
} screen_event_t;

/*
 * Starts the screen task. Pass NULL to use safe defaults.
 * keyboard_init() must also be called once during application startup.
 */
BaseType_t screen_init(const screen_settings_t *initial_settings);

/* Latest-value input. Replaces an older measurement that was not rendered yet.
 */
BaseType_t
screen_update_measurements(const screen_measurements_t *measurements);

/* Replaces the settings shown by the UI, for example after loading Flash. */
BaseType_t screen_set_settings(const screen_settings_t *settings,
                               TickType_t timeout_ticks);

/* Receives requests generated by user actions. Task context only. */
BaseType_t screen_receive_event(screen_event_t *event,
                                TickType_t timeout_ticks);

/* Copies the last settings accepted or committed by the screen module. */
BaseType_t screen_get_settings(screen_settings_t *settings);

/*
 * Asynchronously turns the LCD pixels on/off. The framebuffer and UI state are
 * retained while the display is off.
 */
BaseType_t screen_set_enabled(bool enabled);
BaseType_t screen_turn_on(void);
BaseType_t screen_turn_off(void);

/* Updates only the automatic screen-off settings. Task context only. */
BaseType_t screen_set_auto_off(
    const screen_auto_off_settings_t *auto_off_settings,
    TickType_t timeout_ticks);
